# Generated by Django 5.0.14 on 2025-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
