# Generated by Django 5.0.14 on 2025-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_medicalrecord_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
