# Generated by Django 5.0.14 on 2025-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('case_study', 'Case Study'), ('clinical_review', 'Clinical Review'), ('diagnostic_summary', 'Diagnostic Summary'), ('treatment_outcome', 'Treatment Outcome')], default='case_study', max_length=100)),
                ('report_content', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('doctor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_public', models.BooleanField(default=False, help_text='Mark if this report is shareable')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('related_studies', models.URLField(blank=True, help_text='Link or reference to study')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
