# Generated by Django 5.0.14 on 2025-06-10 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
