# Generated by Django 5.0.14 on 2025-05-28 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional peer comments or feedback'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Mark if this report is shareable'),
        ),
        migrations.AddField(
            model_name='report',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='related_studies',
            field=models.TextField(blank=True, help_text='Links or references to studies'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('case_study', 'Case Study'), ('clinical_review', 'Clinical Review'), ('diagnostic_summary', 'Diagnostic Summary'), ('treatment_outcome', 'Treatment Outcome')], default='case_study', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ManyToManyField(blank=True, related_name='reviewed_reports', to='staff.doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
