# Generated by Django 5.0.14 on 2025-05-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_comments_report_is_public_report_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shared_with',
        ),
    ]
