# Generated by Django 5.0.14 on 2025-06-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_comments_remove_report_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='modified_by',
        ),
    ]
