# Generated by Django 5.0.14 on 2025-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_reviewed_by_report_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='related_studies',
            field=models.URLField(blank=True, help_text='Link or reference to study'),
        ),
    ]
