# Generated by Django 5.0.14 on 2025-06-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_related_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
