# Generated by Django 5.0.14 on 2025-06-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcasestudy',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord'),
        ),
    ]
