# Generated by Django 5.0.14 on 2025-05-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
    ]
