# Generated by Django 5.0.14 on 2025-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Last', max_length=100),
        ),
    ]
